server:
  port: 8082

spring:
  application:
    name: demo-original
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

sombra:
  agent:
    enabled: true
    topic-name: sombra.captured-exchanges
