sombra:
  server:
    topic-name: sombra.captured-exchanges
    candidate-url: http://localhost:8083
  reporting:
    metrics:
      enabled: true
      otlp-endpoint: http://localhost:9090/api/v1/otlp/v1/metrics
    logging:
      enabled: true
      max-value-length: 512

spring:
  docker:
    compose:
      enabled: true
      file: ./compose.yaml
      lifecycle-management: start_only
      readiness:
        timeout: 30s
  kafka:
    bootstrap-servers: localhost:9092
