sombra:
  server:
    topic-name: sombra.captured-exchanges
    candidate-url: http://localhost:8083
    comparison:
      ignored-fields: []
      ignore-array-order: false
      compare-headers: false
      ignored-headers: []

spring:
  docker:
    compose:
      enabled: true
      file: ../compose.yaml
      lifecycle-management: start_only
      readiness:
        timeout: 30s
  kafka:
    bootstrap-servers: localhost:9092
