sombra:
  server:
    ingestion:
      topic-name: sombra.captured-exchanges
    replay:
      candidate-url: http://localhost:8083

spring:
  docker:
    compose:
      enabled: true
      file: ./compose-local.yaml
      lifecycle-management: start_only
      readiness:
        timeout: 30s
  kafka:
    bootstrap-servers: localhost:29092
