spring:
  application:
    name: sombra
  threads:
    virtual:
      enabled: true
  main:
    banner-mode: off
  docker:
    compose:
      enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      auto-offset-reset: earliest
      group-id: sombra-server
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.trusted.packages: com.github.vitorpereiraa.sombra.agent.streaming.dto

sombra:
  agent:
    enabled: false
  server:
    topic-name: ${SOMBRA_TOPIC_NAME}
    candidate-url: ${SOMBRA_CANDIDATE_URL}
  reporting:
    logging:
      enabled: true
      max-value-length: 512

server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[sombra.original.duration]": true
        "[sombra.replay.duration]": true
