spring:
  application:
    name: sombra
  threads:
    virtual:
      enabled: true
  main:
    banner-mode: off
  docker:
    compose:
      enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      auto-offset-reset: earliest

server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info

